package composer_test

import (
	"fmt"
	"os"
	"testing"

	"github.com/yoanm/go-deps-diff/managers/composer"
	"github.com/yoanm/go-deps-diff/shared"
	"github.com/yoanm/go-deps-diff/shared_test"
)

//nolint:maintidx // Low "Maintainability Index" du to deep fixtures
func TestIntegration_SimpleFixtures(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		reqFilePath  string
		lockFilePath string
		expected     shared.PackageMap
	}{
		{
			name:         "Simple",
			reqFilePath:  "./testdata/composer-simple.json",
			lockFilePath: "./testdata/composer-simple.lock",
			expected: map[string]shared.PkgWrapper{
				"vendor/package-a": &shared_test.TestPkgWrapper{
					Name:               "vendor/package-a",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.2.3", Label: "1.2.3"},
					Link:               "https://example.com/wiki/package-a",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/package-b": &shared_test.TestPkgWrapper{
					Name:               "vendor/package-b",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v2.0.0", Label: "v2.0.0"},
					Link:               "https://example.com/wiki/package-b",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/package-c": &shared_test.TestPkgWrapper{
					Name:               "vendor/package-c",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.5.1", Label: "3.5.1"},
					Link:               "https://example.com/package-c",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/package-dev-a": &shared_test.TestPkgWrapper{
					Name:               "vendor/package-dev-a",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.0.0", Label: "1.0.0"},
					Link:               "https://github.com/vendor/package-dev-a",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: true,
				},
				"vendor/package-dev-b": &shared_test.TestPkgWrapper{
					Name:               "vendor/package-dev-b",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v1.1.0", Label: "v1.1.0"},
					Link:               "https://github.com/vendor/package-dev-b",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
			},
		},
		{
			name:         "Complex",
			reqFilePath:  "./testdata/composer-complex.json",
			lockFilePath: "./testdata/composer-complex.lock",
			expected: map[string]shared.PkgWrapper{
				"vendor/pkg-0001": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0001",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.1.1", Label: "2.1.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0001",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0002": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0002",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.2.0", Label: "3.2.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0002",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0003": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0003",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.0.1", Label: "4.0.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0003",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0004": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0004",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.1.0", Label: "1.1.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0004",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0005": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0005",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.2.1-beta.2", Label: "2.2.1-beta.2"},
					Link:               "https://example.com/support-docs/vendor/pkg-0005",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0006": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0006",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.0.0", Label: "3.0.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0006",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0007": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0007",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v3.3.1", Label: "v3.3.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0007",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0008": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0008",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.2.0", Label: "1.2.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0008",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0009": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0009",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.0.1", Label: "2.0.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0009",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0010": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0010",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "86f73d4043691e3b47499100a436fec5ea150a2a",
						Label: "dev-master#86f73d4",
					},
					Link:               "https://example.com/support-wiki/vendor/pkg-0010",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0011": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0011",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.2.1", Label: "4.2.1"},
					Link:               "",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0012": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0012",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.0.0", Label: "1.0.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0012",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0013": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0013",
					Abandoned:          true,
					Version:            shared.PkgVersion{Raw: "2.1.1", Label: "2.1.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0013",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0014": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0014",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v5.2.2", Label: "v5.2.2"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0014",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0015": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0015",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.0.1-beta.0", Label: "4.0.1-beta.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0015",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0016": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0016",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.1.0", Label: "1.1.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0016",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0017": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0017",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.2.1", Label: "2.2.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0017",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0018": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0018",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.0.0", Label: "3.0.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0018",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0019": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0019",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.1.1", Label: "4.1.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0019",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0020": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0020",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "6063a199b704577d953310b513f3011743943b5e",
						Label: "dev-feature/main#6063a19",
					},
					Link:               "https://example.com/support-wiki/vendor/pkg-0020",
					DevOnly:            false,
					RootRequirement:    true,
					RootDevRequirement: false,
				},
				"vendor/pkg-0021": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0021",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v2.1.0", Label: "v2.1.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0021",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0022": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0022",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.1.0", Label: "3.1.0"},
					Link:               "",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0023": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0023",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.2.1", Label: "4.2.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0023",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0024": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0024",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.0.0", Label: "1.0.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0024",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0025": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0025",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.1.1-beta.1", Label: "2.1.1-beta.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0025",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0026": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0026",
					Abandoned:          true,
					Version:            shared.PkgVersion{Raw: "3.2.0", Label: "3.2.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0026",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0027": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0027",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.0.1", Label: "4.0.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0027",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0028": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0028",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v4.0.1", Label: "v4.0.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0028",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0029": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0029",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.2.1", Label: "2.2.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0029",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0030": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0030",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "b8a56915c984281cdd1dc902cacbbaa0c7c81c36",
						Label: "2.9.x-dev#b8a5691",
					},
					Link:               "https://example.com/support-wiki/vendor/pkg-0030",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0031": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0031",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.1.1", Label: "4.1.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0031",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0032": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0032",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.2.0", Label: "1.2.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0032",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0033": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0033",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.0.1", Label: "2.0.1"},
					Link:               "",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0034": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0034",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.1.0", Label: "3.1.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0034",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0035": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0035",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v1.3.2", Label: "v1.3.2"},
					Link:               "https://example.com/support-docs/vendor/pkg-0035",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0036": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0036",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.0.0", Label: "1.0.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0036",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0037": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0037",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.1.1", Label: "2.1.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0037",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0038": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0038",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.2.0", Label: "3.2.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0038",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0039": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0039",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.0.1", Label: "4.0.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0039",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0040": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0040",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "5695761b4841b1e8bc57429ada7d895fdd548051",
						Label: "dev-main#5695761",
					},
					Link:               "https://example.com/support-wiki/vendor/pkg-0040",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0041": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0041",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.2.1", Label: "2.2.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0041",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0042": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0042",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v3.2.0", Label: "v3.2.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0042",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0043": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0043",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.1.1", Label: "4.1.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0043",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0044": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0044",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.2.0", Label: "1.2.0"},
					Link:               "",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0045": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0045",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.0.1-beta.0", Label: "2.0.1-beta.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0045",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0046": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0046",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.1.0", Label: "3.1.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0046",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0047": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0047",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.2.1", Label: "4.2.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0047",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0048": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0048",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.0.0", Label: "1.0.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0048",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0049": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0049",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v5.1.1", Label: "v5.1.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0049",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0050": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0050",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "7e95d646be53792e94a15b5413916b39ab5c8f58",
						Label: "dev-master#7e95d64",
					},
					Link:               "https://example.com/support-wiki/vendor/pkg-0050",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0051": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0051",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.0.1", Label: "4.0.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0051",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0052": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0052",
					Abandoned:          true,
					Version:            shared.PkgVersion{Raw: "1.1.0", Label: "1.1.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0052",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0053": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0053",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.2.1", Label: "2.2.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0053",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0054": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0054",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.0.0", Label: "3.0.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0054",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0055": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0055",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.1.1-beta.1", Label: "4.1.1-beta.1"},
					Link:               "",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0056": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0056",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v2.0.2", Label: "v2.0.2"},
					Link:               "https://example.com/support-source/vendor/pkg-0056",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0057": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0057",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.0.1", Label: "2.0.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0057",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0058": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0058",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.1.0", Label: "3.1.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0058",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0059": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0059",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.2.1", Label: "4.2.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0059",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0060": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0060",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "0e11ad96f8820b9230f093b0f7db8e8017bd9a97",
						Label: "3.1.x-dev#0e11ad9",
					},
					Link:               "https://example.com/support-wiki/vendor/pkg-0060",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0061": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0061",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.1.1", Label: "2.1.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0061",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0062": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0062",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.2.0", Label: "3.2.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0062",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0063": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0063",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v4.3.0", Label: "v4.3.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0063",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0064": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0064",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.1.0", Label: "1.1.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0064",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0065": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0065",
					Abandoned:          true,
					Version:            shared.PkgVersion{Raw: "2.2.1-beta.2", Label: "2.2.1-beta.2"},
					Link:               "https://example.com/support-source/vendor/pkg-0065",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0066": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0066",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.0.0", Label: "3.0.0"},
					Link:               "",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0067": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0067",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.1.1", Label: "4.1.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0067",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0068": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0068",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.2.0", Label: "1.2.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0068",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0069": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0069",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.0.1", Label: "2.0.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0069",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0070": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0070",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "1abd40fc0f178273874183910b1203ac6867db2c",
						Label: "dev-feature/awesome-feature#1abd40f",
					},
					Link:               "https://example.com/support-wiki/vendor/pkg-0070",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0071": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0071",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.2.1", Label: "4.2.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0071",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0072": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0072",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.0.0", Label: "1.0.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0072",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0073": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0073",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.1.1", Label: "2.1.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0073",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0074": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0074",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.2.0", Label: "3.2.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0074",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0075": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0075",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.0.1-beta.0", Label: "4.0.1-beta.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0075",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0076": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0076",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.1.0", Label: "1.1.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0076",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0077": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0077",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v3.1.2", Label: "v3.1.2"},
					Link:               "",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0078": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0078",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.0.0", Label: "3.0.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0078",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0079": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0079",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.1.1", Label: "4.1.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0079",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0080": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0080",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "4599bc2a13ed6bcc3aa8a96e0e4c54174f8be802",
						Label: "2.1.x-dev#4599bc2",
					},
					Link:               "https://example.com/support-wiki/vendor/pkg-0080",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0081": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0081",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.0.1", Label: "2.0.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0081",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0082": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0082",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.1.0", Label: "3.1.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0082",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0083": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0083",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.2.1", Label: "4.2.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0083",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0084": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0084",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v5.0.0", Label: "v5.0.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0084",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0085": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0085",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.1.1-beta.1", Label: "2.1.1-beta.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0085",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0086": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0086",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.2.0", Label: "3.2.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0086",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0087": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0087",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.0.1", Label: "4.0.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0087",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0088": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0088",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.1.0", Label: "1.1.0"},
					Link:               "https://github.com/example/homepage/vendor/pkg-0088",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0089": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0089",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.2.1", Label: "2.2.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0089",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0090": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0090",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "e643d0fa6e8b0a92f19ecce35b77de2d9f9bd749",
						Label: "dev-master#e643d0f",
					},
					Link:               "https://example.com/support-wiki/vendor/pkg-0090",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0091": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0091",
					Abandoned:          true,
					Version:            shared.PkgVersion{Raw: "v2.3.1", Label: "v2.3.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0091",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0092": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0092",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.2.0", Label: "1.2.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0092",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0093": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0093",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.0.1", Label: "2.0.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0093",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0094": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0094",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.1.0", Label: "3.1.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0094",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0095": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0095",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.2.1-beta.2", Label: "4.2.1-beta.2"},
					Link:               "https://example.com/support-source/vendor/pkg-0095",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0096": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0096",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.0.0", Label: "1.0.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0096",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0097": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0097",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.1.1", Label: "2.1.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0097",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0098": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0098",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v4.2.2", Label: "v4.2.2"},
					Link:               "https://example.com/support-source/vendor/pkg-0098",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0099": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0099",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.0.1", Label: "4.0.1"},
					Link:               "",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0100": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0100",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "f72ac1c48716475182f43a1abcafd368791fa11b",
						Label: "dev-master#f72ac1c",
					},
					Link:               "https://example.com/support-wiki/vendor/pkg-0100",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0101": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0101",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.2.1", Label: "2.2.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0101",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: true,
				},
				"vendor/pkg-0102": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0102",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.0.0", Label: "3.0.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0102",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: true,
				},
				"vendor/pkg-0103": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0103",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.1.1", Label: "4.1.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0103",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: true,
				},
				"vendor/pkg-0104": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0104",
					Abandoned:          true,
					Version:            shared.PkgVersion{Raw: "1.2.0", Label: "1.2.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0104",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: true,
				},
				"vendor/pkg-0105": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0105",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v1.1.0", Label: "v1.1.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0105",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: true,
				},
				"vendor/pkg-0106": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0106",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.1.0", Label: "3.1.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0106",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: true,
				},
				"vendor/pkg-0107": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0107",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.2.1", Label: "4.2.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0107",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: true,
				},
				"vendor/pkg-0108": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0108",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.0.0", Label: "1.0.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0108",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: true,
				},
				"vendor/pkg-0109": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0109",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.1.1", Label: "2.1.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0109",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: true,
				},
				"vendor/pkg-0110": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0110",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "e51d682ae5e7d39ffef508f906b4428249476547",
						Label: "1.2.x-dev#e51d682",
					},
					Link:               "",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: true,
				},
				"vendor/pkg-0111": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0111",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.0.1", Label: "4.0.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0111",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0112": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0112",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v3.0.1", Label: "v3.0.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0112",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0113": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0113",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.2.1", Label: "2.2.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0113",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0114": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0114",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.0.0", Label: "3.0.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0114",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0115": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0115",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.1.1-beta.1", Label: "4.1.1-beta.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0115",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0116": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0116",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.2.0", Label: "1.2.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0116",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0117": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0117",
					Abandoned:          true,
					Version:            shared.PkgVersion{Raw: "2.0.1", Label: "2.0.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0117",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0118": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0118",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.1.0", Label: "3.1.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0118",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0119": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0119",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v5.3.2", Label: "v5.3.2"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0119",
					DevOnly:            false,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0120": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0120",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "840b233e8d7917d5e601fd85a7a78a784a487c05",
						Label: "dev-master#840b233",
					},
					Link:               "https://example.com/support-docs/vendor/pkg-0120",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0121": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0121",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.1.1", Label: "2.1.1"},
					Link:               "",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0122": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0122",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.2.0", Label: "3.2.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0122",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0123": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0123",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.0.1", Label: "4.0.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0123",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0124": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0124",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.1.0", Label: "1.1.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0124",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0125": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0125",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.2.1-beta.2", Label: "2.2.1-beta.2"},
					Link:               "https://example.com/support-source/vendor/pkg-0125",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0126": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0126",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v2.2.0", Label: "v2.2.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0126",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0127": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0127",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.1.1", Label: "4.1.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0127",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0128": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0128",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.2.0", Label: "1.2.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0128",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0129": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0129",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.0.1", Label: "2.0.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0129",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0130": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0130",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "b1ab687038b06de2b5b8c572d76307fb7dc1354a",
						Label: "1.2-dev#b1ab687",
					},
					Link:               "https://example.com/support-docs/vendor/pkg-0130",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0131": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0131",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.2.1", Label: "4.2.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0131",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0132": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0132",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.0.0", Label: "1.0.0"},
					Link:               "",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0133": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0133",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v4.1.1", Label: "v4.1.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0133",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0134": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0134",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.2.0", Label: "3.2.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0134",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0135": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0135",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.0.1-beta.0", Label: "4.0.1-beta.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0135",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0136": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0136",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.1.0", Label: "1.1.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0136",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0137": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0137",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.2.1", Label: "2.2.1"},
					Link:               "https://example.com/support-docs/vendor/pkg-0137",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0138": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0138",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.0.0", Label: "3.0.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0138",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0139": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0139",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "4.1.1", Label: "4.1.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0139",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0140": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0140",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "882e270be9da8bec0be5c347ebe1e9a634723b4f",
						Label: "dev-master#882e270",
					},
					Link:               "https://example.com/support-docs/vendor/pkg-0140",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0141": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0141",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.0.1", Label: "2.0.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0141",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0142": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0142",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.1.0", Label: "3.1.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0142",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0143": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0143",
					Abandoned:          true,
					Version:            shared.PkgVersion{Raw: "4.2.1", Label: "4.2.1"},
					Link:               "",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0144": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0144",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.0.0", Label: "1.0.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0144",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0145": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0145",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.1.1-beta.1", Label: "2.1.1-beta.1"},
					Link:               "https://example.com/support-source/vendor/pkg-0145",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0146": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0146",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "3.2.0", Label: "3.2.0"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0146",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0147": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0147",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "v3.3.0", Label: "v3.3.0"},
					Link:               "https://example.com/support-docs/vendor/pkg-0147",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0148": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0148",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "1.1.0", Label: "1.1.0"},
					Link:               "https://example.com/support-source/vendor/pkg-0148",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0149": &shared_test.TestPkgWrapper{
					Name:               "vendor/pkg-0149",
					Abandoned:          false,
					Version:            shared.PkgVersion{Raw: "2.2.1", Label: "2.2.1"},
					Link:               "https://example.com/support-wiki/vendor/pkg-0149",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
				"vendor/pkg-0150": &shared_test.TestPkgWrapper{
					Name:      "vendor/pkg-0150",
					Abandoned: false,
					Version: shared.PkgVersion{
						Raw:   "bcfdbc84c28a5bd099476ce1fe0f4e1d2b0d873a",
						Label: "dev-master#bcfdbc8",
					},
					Link:               "https://example.com/support-docs/vendor/pkg-0150",
					DevOnly:            true,
					RootRequirement:    false,
					RootDevRequirement: false,
				},
			},
		},
	}
	for _, testCase := range tests {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			myMap, err := buildMapFromFixtures(testCase)
			if err != nil {
				t.Fatal(err)
			}

			for _, err := range shared_test.ValidatePackageMap(*myMap, testCase.expected) {
				t.Error(err)
			}
		})
	}
}

func buildMapFromFixtures(testCase struct {
	name         string
	reqFilePath  string
	lockFilePath string
	expected     shared.PackageMap
},
) (*shared.PackageMap, error) {
	// Load fixture files
	simpleReq, err := os.ReadFile(testCase.reqFilePath)
	if err != nil {
		return nil, fmt.Errorf("error while reading requirement file = %w", err)
	}

	simpleLock, err := os.ReadFile(testCase.lockFilePath)
	if err != nil {
		return nil, fmt.Errorf("error while reading lock file = %w", err)
	}

	myMap, err := composer.BuildMapFromBytes(simpleReq, simpleLock)
	if err != nil {
		return nil, fmt.Errorf("error while building map = %w", err)
	}

	return &myMap, nil
}
